base_path: "/Users/kumail/diffdir"

start_runid: "run50"
start_fit_type: "spspop+diffstarpop"

fit_runid: "run52"
fit_type: "diffstarpop+spspop"

epoch:
  n_it: 10
  n_steps: 50
  step_size: 0.1

  feniks_N_z_bins: 3
  feniks_frac_N_centroids: 0.85

  num_halos: 3000

defaults:
  diffstarpop: False
  spspop: False
  ssperr: False
  merging: False
