base_path: "/Users/kumail/diffdir"

start_runid: "run90"
start_fit_type: "all"

fit_runid: "runtest"
fit_type: "diffstarpop+spspop+merging"

feniks:
  num_halos: 100

epoch:
  n_it: 1
  n_steps: 2
  step_size: 0.1
    
defaults:
  diffstarpop: True
  spspop: True
  ssperr: True
  merging: True
