base_path: "/Users/kumail/diffdir"

start_runid: "run73"
start_fit_type: "all"

fit_runid: "run74"
fit_type: "all"

epoch:
  n_it: 1
  n_steps: 25
  step_size: 0.1
  N_z_bins: 1
  N_centroids: 2000
  num_halos: 300
    
defaults:
  diffstarpop: True
  spspop: True
  ssperr: True
  merging: True
