base_path: "/Users/kumail/diffdir"

start_runid: "run90"
start_fit_type: "all"

fit_runid: "runtest"
fit_type: "all"

feniks:
  lh_d_mag: 0.4
  N_centroids: 3000

epoch:
  n_it: 1
  n_steps: 2
  step_size: 0.1
  num_halos: 100
    
defaults:
  diffstarpop: True
  spspop: True
  ssperr: True
  merging: True
