model_drn: /Users/kumail/diffdir/fits/run127
model_nickname: run127_diffstarpop+spspop+merging
fit_diagnostics_save_drn: /Users/kumail/diffdir/fits/run127/diagnostic_plots/diffstarpop+spspop+merging

sdss_drn: /Users/kumail/diffdir/sdss
feniks_drn: /Users/kumail/diffdir/feniks
hizels_drn: /Users/kumail/diffdir/hizels

cosmos20_drn: /Users/kumail/diffdir/COSMOS20
dsps_drn: /Users/kumail/diffdir/COSMOS20/portal.nersc.gov/project/hacc/aphearin/DSPS_data
ssp_file: /Users/kumail/diffdir/ssp_data/ssp_w_emlines/fsps_v0.4.7_mist_c3k_a_kroupa_wNE_logGasU-2.0_logGasZ0.0.h5


plot_sdss: False
plot_feniks: True
plot_hizels: True

plots:
  num_halos : 3000
  plot_insitu_sm: True
  plot_app_mag_funcs: True
  plot_color_pdfs: True
  plot_colors_mags: True
  plot_mags: True
  plot_ssperr: True
  plot_massive_cen_colors: True
  plot_merging_sat_colors: True
  plot_satquench: False
  plot_satquench_model: True
  plot_insitu_smhm: True
  plot_uvj: True
  plot_exsitu_frac: True
  plot_avpop: True
  plot_burstpop: True
  plot_fburst_mh_z: True