model_drn: /Users/kumail/diffdir/fits/run66
model_nickname: run66_all
fit_diagnostics_save_drn: /Users/kumail/diffdir/fits/run66/diagnostic_plots/all

lh_d_mag: 0.6

feniks_drn: /Users/kumail/diffdir/feniks
cosmos20_drn: /Users/kumail/diffdir/COSMOS20
dsps_drn: /Users/kumail/diffdir/COSMOS20/portal.nersc.gov/project/hacc/aphearin/DSPS_data
ssp_file: /Users/kumail/diffdir/ssp_data/ssp_w_emlines/fsps_v0.4.7_mist_c3k_a_kroupa_wNE_logGasU-2.0_logGasZ0.0.h5

plots:
  num_halos : 2500
  plot_colors_mags: False
  plot_mags: False
  plot_ssperr: False
  plot_massive_cen_colors: True
  plot_satquench: False
  plot_satquench_model: True
  plot_insitu_smhm: False
  plot_uvj: False
  plot_exsitu_frac: False
  plot_avpop: False