base_path: "/Users/kumail/diffdir"

start_runid: "run90"
start_fit_type: "all"

fit_runid: "runtest"
fit_type: "all"

feniks:
  lh_d_mag: 0.4
  N_centroids: 100
  num_halos_coarse_zbins: 100
  num_halos_fine_zbins: 100

hizels:
  num_halos: 100

w_feniks: 1.
w_hizels: 1.

epoch:
  n_it: 1
  n_steps: 2
  step_size: 0.1
    
defaults:
  diffstarpop: True
  spspop: True
  ssperr: True
  merging: True
